# This is the main configuration file for the Splatoon plugin

# Do not change this value.  It will cause this file to be replaced
ConfigVersion: 0.10

mysql:
  user: username
  port: 3306
  password: pass
  host: localhost
  database: minecraft

spawnLocation:
  world: ""
  x: 0
  y: 0
  z: 0
  pitch: 0
  yaw: 0

lobbyLocation:
  world: ""
  x: 0
  y: 0
  z: 0
  pitch: 0
  yaw: 0