name: SplatoonMinecraft
main: com.yoerik.SplatoonMinecraft.Splatoon
version: 0.1

commands:
   sp:
      description: The main command for Splatoon
      usage: /sp help
      permission-message: You don't have Splatoon.main

      
